### ISSUE TITLE
feat: Check for existance of the server_files before running SPC

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#19]
When I have deleted server_files, but not serverpackcreator.conf, it hasn't extracted the default server.properties file to server_files folder and produced an exception 
`java.nio.file.NoSuchFileException: server_files/server.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_222]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_222]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_222]
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526) ~[?:1.8.0_222]
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253) ~[?:1.8.0_222]
	at java.nio.file.Files.copy(Files.java:1274) ~[?:1.8.0_222]
	at de.griefed.serverPackCreator.CopyFiles.copyProperties(CopyFiles.java:149) [ServerPackCreator.jar:?]
	at de.griefed.serverPackCreator.Main.main(Main.java:209) [ServerPackCreator.jar:?]
`

**Comment by Griefed** [comment]
lolwhoops

**Comment by whitebear60** [comment]
Oops, markdown in GitHub and Discord is a bit different :)
Fixed formatting of the stacktrace and removed redunant grave accents.

**Comment by Griefed** [comment]
Appears to be related to MacOS. I can not reproduce this on Windows 10 and Linux Ubuntu.

**Comment by Griefed** [comment]
@whitebear60 Can you confirm that this issue is fixed as of https://github.com/Griefed/ServerPackCreator/commit/67a0e612d484f534f8b96d129c56863f81fe61e9 or is this still an issue on macOS?

**Comment by Griefed** [comment]
Lack of feedback leads me to believe that this is no longer an issue. Closing.

Reooen it if it is still an issue with the most current release.
