### ISSUE TITLE
[Bug]: Uploading ZIP-file through webservices fails

### ISSUE THREAD

**Issue by Griefed** [Griefed/ServerPackCreator#240]
### What happened?

I've tried uploading a ZIP-archive of my modpack Survive Create Prosper 4, around 470MB in size.

After a couple of minutes, it stopped uploading and a red triangle, indicating errors was shown.

The browser displays the following error: 

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Proxy.uploadZipFailed (336.d6aa189d.js:1:23364)
    at r (vendor.19a3fb90.js:1:10176)
    at s (vendor.19a3fb90.js:1:10259)
    at L (vendor.19a3fb90.js:1:12233)
    at XMLHttpRequest.a.onreadystatechange (vendor.19a3fb90.js:1:235688)
l @ vendor.19a3fb90.js:1
a @ vendor.19a3fb90.js:1
r @ vendor.19a3fb90.js:1
s @ vendor.19a3fb90.js:1
L @ vendor.19a3fb90.js:1
a.onreadystatechange @ vendor.19a3fb90.js:1
vendor.19a3fb90.js:1 POST https://spc-dev.griefed.de/api/v1/zip/upload net::ERR_HTTP2_PING_FAILED
```

The backend shows no error of any kind.

If anyone has an idea as to what might be the cause of this error, or different error messages, feel free to add them in the comments below.

Everything worked fine when I ran it in a local instance, on my machine. Not behind a reverse proxy though. Maybe the reverse proxy needs to be configured for things like this.

### What did you expect to happen?

I expected the ZIP-file to upload correctly, thus allowing me to generate server pack from it.

### Version

3.0.0-beta.1

### Relevant log output

```shell
> vendor.19a3fb90.js:1 SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Proxy.uploadZipFailed (336.d6aa189d.js:1:23364)
>     at r (vendor.19a3fb90.js:1:10176)
>     at s (vendor.19a3fb90.js:1:10259)
>     at L (vendor.19a3fb90.js:1:12233)
>     at XMLHttpRequest.a.onreadystatechange (vendor.19a3fb90.js:1:235688)
> l @ vendor.19a3fb90.js:1
> a @ vendor.19a3fb90.js:1
> r @ vendor.19a3fb90.js:1
> s @ vendor.19a3fb90.js:1
> L @ vendor.19a3fb90.js:1
> a.onreadystatechange @ vendor.19a3fb90.js:1
> vendor.19a3fb90.js:1 POST https://spc-dev.griefed.de/api/v1/zip/upload net::ERR_HTTP2_PING_FAILED
> g @ vendor.19a3fb90.js:1
> f @ vendor.19a3fb90.js:1
> (anonymous) @ vendor.19a3fb90.js:1
> v @ vendor.19a3fb90.js:1
> Y @ vendor.19a3fb90.js:1
> g @ vendor.19a3fb90.js:1
> r @ vendor.19a3fb90.js:1
> s @ vendor.19a3fb90.js:1
> n @ vendor.19a3fb90.js:1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
It was a problem with the NGINX configuration. A combination of the following settings resolved the issue and allowed for uploading of different sized ZIP-archives:

adding to site-config.conf for ServerPackCreator
```nginx
server {
    ...

    client_max_body_size 0;
    proxy_max_temp_file_size 0;

    ...
}
```

adding to default.conf, port 80
```nginx
server {
    ...
    client_max_body_size 0;
    ...
}
```

adding to default.conf, port 443
```nginx
server {
    ...
    client_max_body_size 0;
    ...
}
```

adding to php-local.ini
```php
upload_max_filesize 512MB
post_max_size 512MB
memory_limit 512MB
```
