### ISSUE TITLE
fix: Add try/catch block for forge/fabric/mc jar download

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#27]
Yesterday the Forge website was down for a few minutes. When I tried to make a ServerPack with Forge, it threw an exception that is listed below and continued its work. Think that when this exception is thrown SPC need to `System.exit(error code)`

`2021-03-17T20:47:02,784 ERROR [main] (ConfigCheck.java:325) - An error occurred during Forge version validation.
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_222]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:1.8.0_222]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_222]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_222]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_222]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_222]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_222]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_222]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_222]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0_222]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0_222]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_222]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[?:1.8.0_222]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_222]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_222]
	at java.net.URL.openStream(URL.java:1057) ~[?:1.8.0_222]
	at de.griefed.ServerPackCreator.ConfigCheck.isForgeVersionCorrect(ConfigCheck.java:288) [classes/:?]
	at de.griefed.ServerPackCreator.CLISetup.setup(CLISetup.java:86) [classes/:?]
	at de.griefed.ServerPackCreator.Main.main(Main.java:18) [classes/:?]
`

**Comment by Griefed** [comment]
Yeah, I had the same experience. Was a nightmare to figure out that it was Forge being down or too slow. It was even more annoying when SPC managed to download the forge-installer partially. The file was there, but useless to SPC, so later down the line, it threw more exceptions.

**Comment by Griefed** [comment]
Copypasta from Discord, by Whitebear60:
```java
try {
ReadableByteChannel readableByteChannel = Channels.newChannel(manifestJsonURL.openStream());
} catch (ConnectException ex) {
appLogger.error("Forge servers is down or unavialable, try running SPC again a few minutes later.");
System.exit(8);
}
```

**Comment by Griefed** [comment]
Reworked the downloading of Fabric and Forge. Should an error occur during the download of the installer.jars, the partially downloaded file will be deleted, which will result in the installation process not entering full production mode. Hopefully prevents issues like the one mentioned above. See https://github.com/Griefed/ServerPackCreator/commit/d0f015aef67be6a552bc54e88db006f06fb99c38
Should any more related issues pop up, please open a new issue :)
