### ISSUE TITLE
[Bug]: Program does not notify user of a Startup crash && Issue Starting

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [Griefed/ServerPackCreator#513]
### What happened?

Should the jar crash in the startup phase, it will simply freeze. 
Maybe some sort of exit would be more appropriate.
This might be an error of my specific type of bug

### What did you expect to happen?

Program should pop up an error message or at least exit to notify the user that something went wrong

### Version

5.1.16

### Relevant log output

```shell
2024-03-01T18:15:41,601  INFO [main] (AbstractPluginManager.java:231) - No plugins
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: getHost(...) must not be null
at de.griefed.serverpackcreator.gui.window.settings.WebserviceSettings.getHost(WebserviceSettings.kt:224)
at de.griefed.serverpackcreator.gui.window.settings.WebserviceSettings.<init>(WebserviceSettings.kt:57)
at de.griefed.serverpackcreator.gui.window.settings.SettingsEditorsTab.<init>(SettingsEditorsTab.kt:63)
at de.griefed.serverpackcreator.gui.window.MainPanel.<init>(MainPanel.kt:66)
at de.griefed.serverpackcreator.gui.window.MainFrame.<init>(MainFrame.kt:48)
at de.griefed.serverpackcreator.gui.MainWindow._init_$lambda$1(MainWindow.kt:78)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "de.griefed.serverpackcreator.gui.window.settings.components.SettingsTitle.hideErrorIcon()" because the return value of "de.griefed.serverpackcreator.gui.window.settings.SettingsEditorsTab.getTitle()" is null
at de.griefed.serverpackcreator.gui.window.settings.components.SettingsCheckTimer$1$1.invokeSuspend(SettingsCheckTimer.kt:51)
at de.griefed.serverpackcreator.gui.window.settings.components.SettingsCheckTimer$1$1.invoke(SettingsCheckTimer.kt)
at de.griefed.serverpackcreator.gui.window.settings.components.SettingsCheckTimer$1$1.invoke(SettingsCheckTimer.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
at de.griefed.serverpackcreator.gui.window.settings.components.SettingsCheckTimer._init_$lambda$0(SettingsCheckTimer.kt:41)
at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@60f4d94, java.util.concurrent.ThreadPoolExecutor@4315e9af[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]]
2024-03-01T18:15:43,312 ERROR [AWT-EventQueue-0] (ConfigEditor.kt:913) - No directories or files specified for copying. This would result in an empty serverpack.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DisruptionSystemsINC** [comment]
Same error also happens when running from AppImage, Maybe a bug with KDE?

**Comment by Griefed** [comment]
Heya,

huh, this is a strange one for sure...
What system are you on? You mentioned KDE, so I guess it some form of Linux distribution.

**Comment by DisruptionSystemsINC** [comment]
Yeah, running on Garuda Linux, kernel version 6.7.6, 64 Bit.
Desktop Environment is Plasma 5.27.10

**Comment by Griefed** [comment]
Could you provide me your `serverpackcreator.properties`, please?

If you've configured a database connection, then make sure to remove the user and password entries and anonymize the JDBC url.

**Comment by DisruptionSystemsINC** [comment]
Confirmed that running the microsoft installer via wine Works perfectly fine

**Comment by DisruptionSystemsINC** [comment]
> Could you provide me your `serverpackcreator.properties`, please?
> 
> If you've configured a database connection, then make sure to remove the user and password entries and anonymize the JDBC url.

Running a Complete fresh install.
Where would the ```serverpackcreator.properties``` be stored?

**Comment by Griefed** [comment]
By default it should reside inside a `ServerPackCreator`-directory in your users home-directory.

**Comment by Griefed** [comment]
Huh, your datasource url points to `spring.datasource.url=/home/mandike/ServerPackCreator/serverpackcreator.db`
Well then, there's the problem! That certainly should not be happening anymore.

I'll get right on it!

**Comment by DisruptionSystemsINC** [comment]
Thank you very much!

**Comment by Griefed** [comment]
New version is on its way!
