### ISSUE TITLE
2.0.7 up thru the 2.2.0-alpha.4

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#71]
It won't make the server pack for me because of this issue everytime that only appears if I run it via console.

```
2021-08-24T16:57:08,969  INFO [AWT-EventQueue-0] (Configuration.java:599) - Checking configuration...
Exception in thread "AWT-EventQueue-0" com.typesafe.config.ConfigException$WrongType: serverpackcreator.tmp: 9: clientMods has type list of LIST rather than list of STRING
        at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:393)
        at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:441)
        at de.griefed.serverpackcreator.Configuration.checkConfigFile(Configuration.java:606)
        at de.griefed.serverpackcreator.gui.CreateServerPackTab.lambda$createServerPackTab$8(CreateServerPackTab.java:721)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kreezxil** [comment]
I think its because one of my mods i selected for the client mods has funny characters in them.

DefaultOptions_1.16.5-12.2.1.jar, IKnowWhatImDoing-3.2.0-forge.jar, ModifierKeyFix-1.0.jar, Neat 1.7-27.jar, ReAuth-1.16-Forge-3.9.3.jar, Toast-Control-1.16.4-4.3.1.jar, [1.16.5][Forge] RPG-HUD-3.8.4.jar, desiredservers-1.16.4-1.0.1.jar, fancymenu_2.2.2-2_MC_1.16.2-1.16.5.jar, journeymap-1.16.5-5.7.3.jar, justenoughkeys-forge-0.2.2.jar, shutupexperimentalsettings-1.0.3.jar, torchoptimizer-1.16.5-2.4.8.jar

such as "[]" and also " ". My guess is that the list on that line needs to be a quote delineated list. ie each element is quoted.

**Comment by kreezxil** [comment]
using that information, i quoted the two I thought were suspect and both had a space in their names. it got past it, I went pack to the alpha and it got past it too.

DefaultOptions_1.16.5-12.2.1.jar, IKnowWhatImDoing-3.2.0-forge.jar, ModifierKeyFix-1.0.jar, **"Neat 1.7-27.jar"**, ReAuth-1.16-Forge-3.9.3.jar, Toast-Control-1.16.4-4.3.1.jar, **"[1.16.5][Forge] RPG-HUD-3.8.4.jar"**, desiredservers-1.16.4-1.0.1.jar, fancymenu_2.2.2-2_MC_1.16.2-1.16.5.jar, journeymap-1.16.5-5.7.3.jar, justenoughkeys-forge-0.2.2.jar, shutupexperimentalsettings-1.0.3.jar, torchoptimizer-1.16.5-2.4.8.jar

**Comment by Griefed** [comment]
Yeah, if a mod has either [ or ] in them, they'll cause problems. Still have to think of a way of reliably escaping them should a user enter mods with those characters in 'em.

**Comment by Griefed** [comment]
For future issues / bug reports, please use the templates. They exist for a reason. 🙂

**Comment by Griefed** [comment]
In the meantime, until I figure out how to reliably autoescape array-indicators like [ and ], try `RPG-HUD-3.8.4.jar` instead of `"[1.16.5][Forge] RPG-HUD-3.8.4.jar`

**Comment by kreezxil** [comment]
It's the space that is the issue, actually, I assumed it was the brackets.
Don't auto-escape, take the lazy way out, force quotes on each filename in
the list.

**Comment by Griefed** [comment]
Will be available in the next alpha release. 🙂

**Comment by Griefed** [comment]
See https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.2 🙂
