### ISSUE TITLE
2.2.0-alpha.4

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#72]
Getting a nullpointer on list of mods to put into server. I have no theories on this one. Will try all the previous versions again until I find one that works.

```
2021-08-24T17:10:59,583  INFO [pool-2-thread-1] (ServerPackHandler.java:583) - Preparing a list of mods to include in server pack...
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
        at de.griefed.serverpackcreator.ServerPackHandler.excludeClientMods(ServerPackHandler.java:591)
        at de.griefed.serverpackcreator.ServerPackHandler.copyFiles(ServerPackHandler.java:515)
        at de.griefed.serverpackcreator.ServerPackHandler.run(ServerPackHandler.java:256)
        at de.griefed.serverpackcreator.swing.TabCreateServerPack.lambda$null$9(TabCreateServerPack.java:866)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
My default java is 8. However I do have 11 and 16. I'll try the latest one and see if that helps at all.

**Comment by kreezxil** [comment]
log: https://pastebin.com/V4PmdJwK

**Comment by kreezxil** [comment]
just tried alpha.3 and I noticed that it strips out the quotes from the client list. I'll stop here for now. I think it'll be solid once this and the other issue are addressed.

**Comment by kreezxil** [comment]
tested this one down 2.0.6. 

2.0.6 has no issues save the need to quote client mod names, it actually creates the pack.

**Comment by Griefed** [comment]
For future issues / bug reports, please use the templates. They exist for a reason. 🙂

**Comment by Griefed** [comment]
I believe the issue here is your serverpackcreator.properties not having the `de.griefed.serverpackcreator.serverpack.autodiscoverenabled=true`

the default one should look something like this:
```
lang=en_us
de.griefed.serverpackcreator.configuration.fallbackmodslist=AmbientSounds,BackTools,BetterAdvancement,BetterFoliage,BetterPing,BetterPlacement,Blur,cherished,ClientTweaks,Controlling,CTM,customdiscordrpc,CustomMainMenu,DefaultOptions,durability,DynamicSurroundings,EiraMoticons,FullscreenWindowed,itemzoom,itlt,jeiintegration,jei-professions,just-enough-harvestcraft,JustEnoughResources,keywizard,modnametooltip,MouseTweaks,multihotbar-,Neat,OldJavaWarning,PackMenu,preciseblockplacing,ResourceLoader,SimpleDiscordRichPresence,SpawnerFix,timestamps,TipTheScales,WorldNameRandomizer
de.griefed.serverpackcreator.configuration.hastebinserver=https://haste.zneix.eu/documents
de.griefed.serverpackcreator.serverpack.autodiscoverenabled=true
```

Either delete your `serverpackcreator.properties` and try again, or edit the already existing one. If you could try that and report back to me, that would be awesome.
