### ISSUE TITLE
3.0.0-alpha.2 and .1 crashing

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#75]
* **What is the current behavior?**

It's doing this in shell before crashing out.
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.typesafe.config.ConfigException$WrongType: serverpackcreator.conf: 9: clientMods has type list of LIST rather than list of STRING
        at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:393)
        at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:441)
        at de.griefed.serverpackcreator.swing.TabCreateServerPack.loadConfig(TabCreateServerPack.java:1035)
        at de.griefed.serverpackcreator.swing.TabCreateServerPack.createServerPackTab(TabCreateServerPack.java:582)
        at de.griefed.serverpackcreator.swing.SwingGuiInitializer.<init>(SwingGuiInitializer.java:169)
        at de.griefed.serverpackcreator.Main.main(Main.java:279)
        ... 8 more
```

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

running it with java 8, 11, and 16, all same result, just one step, run it. I suspect because it is Sunday, that CF and whomever you're using to pull from, has done something with their api again.

* **Please tell us about your environment:**

-  
```Your Operating System: Manjaro Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.12.19-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
```
- Your Java version: **I use all three of these** `java, java11, java16`
- Your ServerPackCreator version: 3.0.0-alpha.2
- Your config file:  https://gist.github.com/9288cd3314efadec76ced0e2aa369b37

- Your latest log file:  https://gist.github.com/7a33e2636cd16d76f066444eb6d82e1b

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
* The console output: https://gist.github.com/kreezxil/bc433ce84b5b8c903b7a91a01ac001f2

**Comment by kreezxil** [comment]
this maybe a dead issue already, I deleted the serverpackcreator.conf and properties and then it ran.

**Comment by Griefed** [comment]
Probaby an issue with client mods and special characters `Caused by: com.typesafe.config.ConfigException$WrongType: serverpackcreator.conf: 9: clientMods has type list of LIST rather than list of STRING` which usually happens if a mod has either [ or ] in their name. Fixed in the newest version, though, as it encapsulated each element wiht "".

**Comment by kreezxil** [comment]
it worked with a refreshed config and properties file which is why i closed
it.

**Comment by Griefed** [comment]
Feel free to reopen this issue if it happens agan, even with the new way configs are written now.

If a config had bad values before this release, the error will appear, but it shouldn't happen with the new configs due to how each element in the lists are stored.
